### ISSUE TITLE
建议require函数增加onerror错误处理

### ISSUE THREAD

**Issue by wayne-chan2** [ecomfe/esl#27]
看见源码中提到“因为高级浏览器在devtool的console面板会报错，再throw一个Error多此一举了”。

实际并非多此一举，在 onerror 回调函数里可关闭某些界面元素（因为它依赖的JS未导入），另外当访问A站点不可达时，可继续尝试B站点，现实一个应用就是国外A站被GFW封闭（或高峰期不可达），转而向国内后备站点发请求。

虽然 require(deps, callback, errback) 第3个参数并非 AMD要求，但 requirejs 实现了这个接口，它不是同步throw Error，而是异步回调errback函数。

**Comment by errorrik** [comment]
这是一个很好的建议，此issue我们会一直打开，直到我们考虑清楚支持或者不支持此feature。

在此之前，可以先通过如下方式解决：

> 在 onerror 回调函数里可关闭某些界面元素（因为它依赖的JS未导入）

初始化时元素为关闭，相应js模块初始化时执行打开行为

> 当访问A站点不可达时，可继续尝试B站点，现实一个应用就是国外A站被GFW封闭（或高峰期不可达），转而向国内后备站点发请求

这种情况我觉得不应该在前端解决，尽量在部署和网络层考虑。

**Comment by zhump** [comment]
<script src="js/esl.js"></script> 
		<script type="text/javascript">
			require(['js/config'],function(c){
				//js config 是我总配置文件
				//我一般用requirejs的时候去拉一下这个js,拉来下再拉
				//require(['module/m2']);
				
				//但好像发现esl 并不支持这种写法啊。。。。
			})
		</script>

**Comment by errorrik** [comment]
经过讨论，决定不支持此特性。抱歉。so issue关闭
