### ISSUE TITLE
建议保留对自定义loader名字的支持

### ISSUE THREAD

**Issue by 21paradox** [ecomfe/esl#28]
如题。
建议保留loader的支持，有些页面使用了seajs/modjs作为加载器，建议esl保留自定义loader功能，这样第三方代码能够可以有自定义加载器来管理模块。

**Comment by errorrik** [comment]
esl有自己的loader名字，就叫做`esl`。

但是，AMD和CMD对于模块的定义，都使用了`define`，它们都依赖全局的`define`，所以在一个页面上，是不能并存的。其他非AMD和CMD但是使用了`define`的loader也一样。所以，对于Web应用，还是建议已开始就选择好使用什么样的模块定义标准

**Comment by 21paradox** [comment]
好的，感谢回复。
