### ISSUE TITLE
esl  如何做多个请求concat？

### ISSUE THREAD

**Issue by rubyless** [ecomfe/esl#30]
请问 如何做多个请求concat？

**Comment by otakustay** [comment]
contact应该在build时期做，而esl是运行期的，你需要的是不是[edp-build](https://github.com/ecomfe/edp-build)，相关文档在[这里](https://github.com/ecomfe/edp/wiki/Build)

**Comment by errorrik** [comment]
请求合并需要你构建的时候通过工具处理好。通常情况会将模块声明合并到入口模块，入口模块只有一个。工具可以选择r.js或者edp。

如果你有交叉，需要配置`bundles`项。这个配置项的运行逻辑和requirejs一样。
`bundles`可以参考 https://github.com/ecomfe/esl/blob/master/doc/config.md ，也可以参考requirejs的文档

**Comment by rubyless** [comment]
好的，多谢！
