### ISSUE TITLE
esl 2.0.2疑似bug

### ISSUE THREAD

**Issue by gudaozr** [ecomfe/esl#31]
开发者您好！我在使用esl 2.0.2的过程中发现了一个bug，即使用require函数时，模块的文件名中如果包含“.”，则模块可以加载成功，但无法执行成功后的回调函数。例如“jquery-1.11.1”。烦请核实。谢谢！

**Comment by errorrik** [comment]
经过测试，不是bug。

```html
<script>
require(['test.mod'], function (mod) {
    alert(mod.name)
});
</script>
```

```javascript
// test.mod.js
define({name:'test.mod'});
```

另，经过分析，jquery的源码中是通过具名id的方式声明模块的:

```javascript
define("jquery",[], ...);
```

如果你是 `require(['jquery-1.11.1'])`， 那么很明显，肯定是不行的，因为声明的模块是jquery而不是jquery-1.11.1。

解决办法是：既然模块名和其路径不是完全对应的，那么可以通过paths配置项配置下

```html
<script src="esl.js"></script>
<script>
require.config({
    paths: {
        jquery: 'path/jquery-1.11.1'
    }
});
require(['jquery'], function (jquery) {
    // ......
});
</script>
```

**Comment by gudaozr** [comment]
非常感谢您的回复和解惑！水平有限，给您添麻烦了！

**Comment by errorrik** [comment]
不会，能解决问题就好
