### ISSUE TITLE
关于currentlyAddingScript的问题

### ISSUE THREAD

**Issue by 24wangchen** [ecomfe/esl#32]
你好，关于currentlyAddingScript，我看到你是借鉴require.js中的写法。
将node赋值于currentlyAddingScript，是为了产生闭包这么写的么，注释中写道在ie6-8中因为某些缓存，导致script执行先于appendChild完成，不知道这个会导致什么bug呢？困扰了一晚上，还是没能想明白，希望予以解答，多谢多谢！

**Comment by errorrik** [comment]
首先明确一点，该功能只有针对`匿名定义的模块`才有用。`具名定义的模块`已经指明id，不需要进行获取。

----------


当你动态append一个script的时候，运行顺序是这样的

1. script execute
2. script onload emit

所以，当你的script中，是一个`匿名定义的模块`时，步骤`1`把dependencies和factory缓存到某个地方，步骤`2`可以根据闭包中的id，加上步骤`1`缓存的dependencies和factory，去实际声明模块。

到此，一切都没问题。但是，当你发起了多个模块的请求，比如a和b，是否能够保证顺序如下呢？

1. a script execute
2. a script onload emit
3. b script execute
4. b script onload emit

很不幸，答案是否定的。IE中，可能会出现这样的顺序：

1. a script execute
2. b script execute
3. a script onload emit
4. b script onload emit

如果我们再使用上面的策略，就会有问题。当步骤`3`执行的时候，其实是用`b`的dependencies和factory，去声明`a`模块。

所以，解决方案是，在步骤1和步骤2的时候，即使使用`匿名定义模块`，我们也要通过检测当前运行的script是什么模块发起的请求，使用这个模块id去声明模块。这就是`currentlyAddingScript`的作用

**Comment by 24wangchen** [comment]
大神起好早，多谢指点，我消化消化^_^

**Comment by 24wangchen** [comment]
我结合这篇文章http://www.guypo.com/ies-premature-execution-problem/，明白了那段代码。原来是ie缓存script后，执行顺序就变了，只有插入到document后，才会执行，所以此时currentlyAddingScript就上场了，应该是这么理解吧？@errorrik
