### ISSUE TITLE
https://github.com/ecomfe/esl 最上面的 esl 是 2.0.4

### ISSUE THREAD

**Issue by tcdona** [ecomfe/esl#43]
源码里面有个 dist/output 目录自动化处理一下压缩版本的输出？
 loadplugin tpl.js 只能自己写一个吗，有没有在用的提供呢

**Comment by errorrik** [comment]
最新版本是2.0.6，抱歉上面的地址忘记改了。github上src目录的是source，如果你想要压缩版本，可以直接从下面地址下载：

http://s1.bdstatic.com/r/www/cache/ecom/esl/2-0-6/esl.js

loader plugin还是需要自己写的，esl本身没法提供tpl这样一个 plugin，因为各种系统使用的模板引擎都会不一样。
