### ISSUE TITLE
esl正则匹配注释时截断代码，导致后续require无法预先加载

### ISSUE THREAD

**Issue by li-yinan** [ecomfe/esl#50]
代码中存在s/\//g类似的正则表达式时，匹配注释会被匹配到，后续代码中require不会被检测到，导致运行时找不到模块
如：var reg = s/\//g; require('xxx'); 运行时提示module xxx missing

**Comment by errorrik** [comment]
这个现象在当前行require前的语句中，出现`//`字样时会发生，是已知现象。

通过正则去排除注释掉的require是不严谨的，但是这并不会存在问题。原因如下：

1. AMD规定，当dependencies参数不存在时，需要扫描function body，通过正则匹配，找出依赖的模块。这种使用模式发生在 **开发过程中** 。但是在开发过程中，通常要求较好的代码风格，一个语句一行是基本要求。所以这个现象不会触发。
2. 在 **线上环境**，代码通常会被压缩成一行，require的前面很可能出现`//`字样。但是，**线上环境**的AMD模块应该经过编译，dependencies在编译过程应该被补齐。当出现dependencies参数时，loader不应该再扫描function body，直接以dependencies为准。所以这个现象也不会触发。

另外，由于前端应用对体积要求较高，不可能在loader里写一个完整的parser。

综上，该现象不是bug，无法修改。
