### ISSUE TITLE
配置了 paths 的模块中依赖的相对路径处理不符合预期

### ISSUE THREAD

**Issue by Exodia** [ecomfe/esl#53]
如下：
```javascript
// main.html
require.config({
            'baseUrl': 'src',
            'paths': {
                'tpl': 'common/tpl'
            }
});

// common/tpl.js
define(function(require){
      var filter = require('./filter');
});
```

期望 filter 的加载路径是 src/common/filter.js，而实际加载了src/filter.js

**Comment by errorrik** [comment]
如果你是`require(['tpl'])`，那是符合预期的。paths配置能影响的纯粹是module id->url的路径查找过程。

tpl的./filter，module id是filter。而paths并没有相关配置，所以会从baseUrl下找。

另外， **不要使用paths** 。见http://efe.baidu.com/blog/dissecting-amd-how/
