### ISSUE TITLE
尝试升级2.1.2，报错了

### ISSUE THREAD

**Issue by yankun01** [ecomfe/esl#56]
https://github.com/ecomfe/esl/blob/master/src/esl.js#L557

出错的代码
var Ajax = require('eoo').create(require('mini-event/EventTarget'), exports);
发现2.1.0没有这个问题，2.1.2问题存在，简单排查了一下问题在这一行。供参考。修改为上一版本后正常了。

如需详情，另外提供。

**Comment by yankun01** [comment]
https://github.com/ecomfe/esl/pull/57

**Comment by errorrik** [comment]
在这里做个记录，简单说明下。

场景是这样的，一个async require中有多个模块，并且模块之间有包含依赖时，会发生MODULE MISS，但是依赖关系看起来是没问题的。

出错的原因在于，module的prepare过程中对prepared状态的判断。这个过程是向下递归的，为了解决循环依赖，这个过程会纪录正在处理的module，如果模块发现自己正在被处理，说明在一个循环依赖环里，这时直接返回true。但是处理完的模块没有置回状态，导致一个模块在二次prepare时，直接返回true了。

在一个async require只有一个模块时，没出错的原因是依赖里总有一个未ready的，所以不会开始初始化模块。而原先的熔断机制（发现某个依赖模块没准备好时，后面就不尝试了）也掩盖了这个错误，让这个bug永远不会出现。直到2.1.2，为了提示信息更完善，去掉了熔断机制，让这个隐藏深处的bug暴露出来了。
