### ISSUE TITLE
esl在一些特殊情况下无法加载module

### ISSUE THREAD

**Issue by kekee000** [ecomfe/esl#60]
在包含地址信息的代码里，如果不注意书写顺序，模块在编译之后压缩成一行运行，会导致依赖模块无法加载。
希望增加此类信息提示，以便于排查错误。
```javascript
var pic = '//xxx.png';
require('a');
```

**Comment by erik168** [comment]
已知情况，AMD设计时就考虑到的情况，非问题。

1. 开发时，代码是多行的，所以 // 单行注释不会导致问题
2. 线上环境，模块经过编译，define 具有 dependencies 参数，函数体中的require literal不会被loader作为装载依据，也不存在问题。

总之，从开发环境到线上，AMD模块需要经过编译过程，否则，就不要压缩成一行。
