### ISSUE TITLE
一个比较严重的bundle bug, header上多次添加同一bundle模块url

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esl#61]
``` js
// src/main.js
==========
define('A', {}); define('B', {}); define('C', {});
==========

// esl config
==========
baseUrl: src,
bundles: {
    main: ['A', 'B', 'C']
}
==========

 // console输入
require(['A']); require(['B']);

// 结果
==========
```

<img width="790" alt="d868df7d8196ecdfaaa803f61" src="https://cloud.githubusercontent.com/assets/10464981/16900613/eb31e61c-4c5b-11e6-97e4-52515f9055ba.png">

**Comment by erik168** [comment]
抱歉过这么久才处理，事情太多了。当时我测试过这个东西，确实是有两个script，但是是发的一个请求，所以这事交给浏览器解决了。

**Comment by uraincay** [comment]
能否合并下，应该不是所有浏览器都是一个请求的

**Comment by leeight** [comment]
简单的测试了一下，感觉应该只有 firefox 下面不太正常，chrome，ie9, ie10 好像是正常的

http://output.jsbin.com/vatidaviso

**Comment by leeight** [comment]
貌似最新的 2-2-0 已经没问题了
